//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public InventoryItem()
        {
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public string ItemQty { get; set; }
        public System.DateTime ItemPurchaseDate { get; set; }
        public System.DateTime ItemExpirydate { get; set; }
        public int Inventory_InventoryId { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
