//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
            this.Users = new HashSet<User>();
        }
    
        public int OrderNo { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public double ProductQty { get; set; }
        public double TotalPrice { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
