//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPlaced
    {
        public OrderPlaced()
        {
            this.PlacedOrderItems = new HashSet<PlacedOrderItem>();
        }
    
        public int OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double OrderPrice { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDoneTime { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public int UserId { get; set; }
        public string ItemIds { get; set; }
    
        public virtual ICollection<PlacedOrderItem> PlacedOrderItems { get; set; }
    }
}
