//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacedOrderItem
    {
        public int Id { get; set; }
        public int OrderNo { get; set; }
        public int OrderItemid { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual OrderPlaced OrderPlaced { get; set; }
    }
}
