//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.InventoryItems = new HashSet<InventoryItem>();
        }
    
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string VendorPhoneNo { get; set; }
        public string VendorEmail { get; set; }
        public string VendorAddress1 { get; set; }
        public string VendorAddress2 { get; set; }
        public string VendorCity { get; set; }
        public string VendorProvince { get; set; }
        public string VendorPostal { get; set; }
    
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
    }
}
