//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.InventoryItems = new HashSet<InventoryItem>();
            this.Products = new HashSet<Product>();
        }
    
        public int InventoryId { get; set; }
        public string InventoryItem { get; set; }
        public string InventoryDesc { get; set; }
        public string InventoryQty { get; set; }
        public string InventoryPrice { get; set; }
    
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
