//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Menus = new HashSet<Menu>();
            this.Inventories = new HashSet<Inventory>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public System.DateTime ProductExpiryDate { get; set; }
    
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
